[MI-2626]: Improved the UI for GroupedPartOutputControl type response from VA
Brightscout/mattermost-plugin-servicenow-virtual-agent pull request #19
Opened 2023-02-01 07:00 UTC by Nityanand13

2023-02-01 11:48 UTC, raghavaggarwal2308 requested changes

2023-02-01 11:48 UTC, raghavaggarwal2308 commented on server/plugin/virtual_agent.go
>  	}
```suggestion
	}
	
```

2023-02-01 11:48 UTC, raghavaggarwal2308 commented on server/plugin/virtual_agent.go
> +	return nil
There is a function "DM" available for this, use that here!

2023-02-07 05:36 UTC, raghavaggarwal2308 requested changes

2023-02-07 05:36 UTC, raghavaggarwal2308 commented on server/plugin/virtual_agent.go
> +	if _, err := p.dm(userID, &model.Post{
Use "p.DM"

2023-02-14 06:37 UTC, raghavaggarwal2308 approved these changes

2023-02-14 07:28 UTC, manojmalik20 approved these changes

2023-02-14 07:28 UTC, manojmalik20 commented on server/plugin/virtual_agent.go
> +	for id, value := range res.Values {
```suggestion
	for index, value := range res.Values {
```

2023-02-15 07:39 UTC, manojmalik20 approved these changes

2023-02-15 12:44 UTC, merged